CREATE TABLE IF NOT EXISTS Websites (
	ID		UNSIGNED INT	NOT NULL,
	Name		VARCHAR(32)	NOT NULL,
	BaseUrl		VARCHAR(256)	NOT NULL,
	AllMangasUrl	VARCHAR(256)	NOT NULL,
	MangaUrlFormat	VARCHAR(256)	NOT NULL,
	ChapterUrlFormat VARCHAR(256)	NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS Authors (
	ID		UNSIGNED INT	NOT NULL	AUTO_INCREMENT,
	RomajiName	VARCHAR(32)	NOT NULL,
	KanjiName	VARCHAR(32),
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS Mangas (
	ID		UNSIGNED INT	NOT NULL	AUTO_INCREMENT,
	Website		UNSIGNED INT	NOT NULL,
	Author		UNSIGNED INT	NOT NULL,
	FullName	VARCHAR(32)	NOT NULL,
	UrlName		VARCHAR(32)	NOT NULL,
	Synopsis	TEXT,
	LastDownload	DATETIME,
	PRIMARY KEY (ID),
	FOREIGN KEY (Website) REFERENCES Websites(ID),
	FOREIGN KEY (Author)  REFERENCES Authors(ID)
);

CREATE TABLE IF NOT EXISTS Chapters (
	ID		UNSIGNED INT	NOT NULL	AUTO_INCREMENT,
	Manga		UNSIGNED INT	NOT NULL,
	No		UNSIGNED INT	NOT NULL,
	Title		VARCHAR(256),
	Complete	BOOL		DEFAULT false,
	DownloadDate	DATETIME	DEFAULT ON UPDATE,
	PRIMARY KEY (ID),
	FOREIGN KEY (Manga) REFERENCES Mangas(ID)
);

